version: "3.1"

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  platform:
    links:
      - crm
    ports:
      - 4000:4000
    build: ./platform
    environment:
      crm: crm
  crm:
    environment:
      DB_URL: ${DB_URL}
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    build: ./crm
