version: "3.1"

services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  platform:
    links:
      - crm
    ports:
      - 4000:4000
      - 5000:4567
    build: ./platform
    environment:
      crm: crm
  crm:
    environment:
      DB_URL: ${DB_URL}
    depends_on:
      - mongodb
    links:
      - redis
    ports:
      - 3000:3000
    build: ./crm
